### ISSUE TITLE
How to get access to the google doc provided by https://cs128.netlify.app/

### ISSUE THREAD

**Issue by Algoroxyolo** [mersaults/uiuc-cs-wiki#5]
As I was trying to get access to the google doc, the website told me that I have no access to the files. How can I get access to the lecture and notes inside the google doc?

**Comment by mersaults** [comment]
Looks like the instructor for the course has locked off access to the spreadsheet for all non @illinois.edu email addresses. Since all of the material on that spreadsheet is publicly available anyways (which tells me that the instructor doesn't want to make the materials closed-source), I've made a copy of the spreadsheet and I will update the relevant parts of the guide accordingly. Thanks for pointing this out!

**Comment by Algoroxyolo** [comment]
Where can I get the new copy?

**Comment by Algoroxyolo** [comment]
> Looks like the instructor for the course has locked off access to the spreadsheet for all non @illinois.edu email addresses. Since all of the course material on that spreadsheet is publicly available anyways (which tells me that the instructor doesn't want to make the materials closed-source), I've made a copy of the spreadsheet and I will update the relevant parts of the guide accordingly. Thanks for pointing this out!

Great thanks to the effort. Where can I get access to the spreadsheet?

**Comment by mersaults** [comment]
> > Looks like the instructor for the course has locked off access to the spreadsheet for all non @illinois.edu email addresses. Since all of the course material on that spreadsheet is publicly available anyways (which tells me that the instructor doesn't want to make the materials closed-source), I've made a copy of the spreadsheet and I will update the relevant parts of the guide accordingly. Thanks for pointing this out!
> 
> Great thanks to the effort. Where can I get access to the spreadsheet?

[Here's](https://docs.google.com/spreadsheets/d/1knMPwtQUAfuS8aZpWrZZ0kqhK3sd3G0NqMGe3_FSPy0/edit?usp=sharing) the link.
